#!/bin/sh

echo "Switching to branch main"
git checkout main

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ root@170.187.193.117:/var/www/html/portfolio.godbehere.org/
echo "Deployment complete"